### ISSUE TITLE
Adding RKE metric to the repository

### ISSUE THREAD

**Issue by mjalali** [layer6ai-labs/dgm-eval#6]
Hello,
I wanted to recommend you add RKE to the repository.

Here is the like:
[https://github.com/mjalali/renyi-kernel-entropy](https://github.com/mjalali/renyi-kernel-entropy)

**Comment by JesseCresswell** [comment]
Hello there, if you would like your metric added to the codebase, please submit a pull request following the structure and style of the other metrics we have implemented.
